Numpy : Practice Problem

1. Extract all odd numbers from arr


In [25]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [68]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [11]:
arr=np.arange(10)
np.reshape(arr,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

4. Stack arrays a and b vertically

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [86]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [69]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49.

In [64]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [58]:
a=np.random.randn(10,10)
print(a.min())
print(a.max())

-2.137406389303483
2.659750575146562


9. Create a 3*3 matrix and print it's transpose matrix

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.T)
np.transpose(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

10. Create two arrays of 2-D and find dot product of it.

In [55]:
a = np.array([[1,2],
               [2,1]])
b = np.array([[2,1],
               [1,2]])
np.dot(a,b)

array([[4, 5],
       [5, 4]])

11. Compute the maximum for each row in the given array.

In [57]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
a.max(axis=1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [21]:
data = np.random.randint(10,100,(5,4))
data[[2,4],2:3]

array([[22],
       [47]])

13. Convert below matrix into vector

In [19]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

14. The product of two inverse matrix is identical matrix,prove

In [83]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
np.array(np.dot(m,n), dtype=int)

array([[1, 0],
       [0, 1]])

15. Create a matrix from a uniform distribution over [0, 1)

In [84]:
data = np.random.uniform(0,1,(2,2))
data

array([[0.95252414, 0.97543482],
       [0.4269334 , 0.49793281]])